#Pre-commit config
#This config uses the pre-commit tool to automatically format files
#on commit. If you have the pre-commit CLI installed, just run the command
#"pre-commit install". See the README for more information.
repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
