#Pre-commit config
#This config uses the pre-commit tool to automatically format files
#on commit. If you have the pre-commit CLI installed, just run the command
#"pre-commit install". See the README for more information.
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
